FROM python:3.12

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

COPY reqs.txt /app/
RUN pip install -r reqs.txt

COPY core/ /app/core/
COPY kajimasoys_portfolio/ /app/kajimasoys_portfolio/
COPY media/ /app/media/
COPY pages/ /app/pages/
COPY service/ /app/service/
COPY manage.py /app/

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]