# Первая стадия: Vue
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY client/package*.json ./
RUN npm install
COPY client/ .

ARG NODE_OPTIONS=--max-old-space-size=2048
RUN node --max-old-space-size=2048 /usr/local/bin/npm run build

# Вторая стадия: Nginx
FROM nginx:stable-alpine
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html
