# Generated by Django 4.1.5 on 2023-02-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Описание (рус.)'),
        ),
        migrations.AddField(
            model_name='project',
            name='git',
            field=models.URLField(blank=True, verbose_name='Ссылка на гит'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ru',
            field=models.CharField(default='Проект', max_length=250, verbose_name='Название проекта (рус.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название проекта (англ.)'),
        ),
    ]
