# Generated by Django 4.1.5 on 2023-02-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_description_ru_project_git_project_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
