# Generated by Django 4.1.5 on 2023-02-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='personal',
            field=models.BooleanField(default=False, verbose_name='Персональный проект? (Вадима?)'),
        ),
    ]
