# Generated by Django 4.1.5 on 2023-02-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_personal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_edit_personal_project', 'Can edit personal project')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
