# Generated by Django 4.1.5 on 2023-02-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
