# Generated by Django 4.1.5 on 2023-03-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('skill_type', models.CharField(default='backend', max_length=15, verbose_name='Типа навыка')),
                ('name', models.CharField(max_length=250, verbose_name='Навык (англ.)')),
                ('name_ru', models.CharField(max_length=250, verbose_name='Навык (рус.)')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Описание (англ.)')),
                ('description_ru', models.TextField(blank=True, max_length=5000, verbose_name='Описание (рус.)')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активен?')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
