# Generated by Django 4.1.5 on 2023-03-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('other', 'Other')], default='backend', max_length=15, verbose_name='Типа навыка'),
        ),
    ]
