# Generated by Django 4.1.5 on 2023-03-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='en', max_length=6, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Страница о себе',
                'verbose_name_plural': 'Страницы о себе',
            },
        ),
        migrations.CreateModel(
            name='CookieElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='en', max_length=6, verbose_name='Язык')),
                ('element_text', models.CharField(max_length=30, verbose_name='Текст')),
                ('link', models.CharField(max_length=30, verbose_name='Ссылка')),
                ('button', models.CharField(max_length=30, verbose_name='Кнопка')),
            ],
            options={
                'verbose_name': 'Всплывающее окно cookie',
                'verbose_name_plural': 'Всплывающие окна cookie',
            },
        ),
        migrations.CreateModel(
            name='CookiesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='en', max_length=6, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Страница с cookies',
                'verbose_name_plural': 'Страницы с cookies',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='en', max_length=6, verbose_name='Язык')),
                ('overview_link', models.CharField(max_length=30, verbose_name='Обзор')),
                ('projects_link', models.CharField(max_length=30, verbose_name='Проекты')),
                ('skills_link', models.CharField(max_length=30, verbose_name='Скиллы')),
                ('about_link', models.CharField(max_length=30, verbose_name='Обо мне')),
                ('terms_link', models.CharField(max_length=30, verbose_name='Условия')),
                ('privacy_link', models.CharField(max_length=30, verbose_name='Конфиденциальность')),
                ('cookies_link', models.CharField(max_length=30, verbose_name='Cookies')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футеры',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='en', max_length=6, verbose_name='Язык')),
                ('contact_button', models.CharField(max_length=20, verbose_name='Свяжитесь со мной')),
                ('projects_button', models.CharField(max_length=20, verbose_name='Проекты')),
                ('get_started_button', models.CharField(max_length=20, verbose_name='Начните')),
                ('learn_more_button', models.CharField(max_length=20, verbose_name='Узнать больше')),
                ('send_message_button', models.CharField(max_length=20, verbose_name='Отправить заявку')),
                ('main_title', models.CharField(max_length=150, verbose_name='Заголовок главной секции')),
                ('introduce_title', models.CharField(max_length=150, verbose_name='Заголовок секции вступления')),
                ('introduce_description', models.CharField(max_length=300, verbose_name='Описание секции вступления')),
                ('project_title', models.CharField(max_length=150, verbose_name='Заголовок секции проектов')),
                ('project_description', models.CharField(max_length=300, verbose_name='Описание секции проектов')),
                ('stages_title', models.CharField(max_length=150, verbose_name='Заголовок секции стадий разработки')),
                ('discussion_title', models.CharField(max_length=50, verbose_name='Заголовок обсуждения')),
                ('discussion_description', models.CharField(max_length=500, verbose_name='Описание обсуждения')),
                ('concept_title', models.CharField(max_length=50, verbose_name='Заголовок концепта')),
                ('concept_description', models.CharField(max_length=500, verbose_name='Описание концепта')),
                ('server_dev_title', models.CharField(max_length=50, verbose_name='Заголовок разработки сервера и бд')),
                ('server_dev_description', models.CharField(max_length=500, verbose_name='Описание разработки сервера и бд')),
                ('ui_dev_title', models.CharField(max_length=50, verbose_name='Заголовок разработки UI')),
                ('ui_dev_description', models.CharField(max_length=500, verbose_name='Описание разработки UI')),
                ('test_title', models.CharField(max_length=50, verbose_name='Заголовок тестирования')),
                ('test_description', models.CharField(max_length=500, verbose_name='Описание тестирования')),
                ('deploy_title', models.CharField(max_length=50, verbose_name='Заголовок деплоя')),
                ('deploy_description', models.CharField(max_length=500, verbose_name='Описание деплоя')),
                ('first_string', models.CharField(max_length=20, verbose_name='Первая часть слогана')),
                ('second_string', models.CharField(max_length=20, verbose_name='Вторая часть слогана-ссылка')),
                ('third_string', models.CharField(max_length=20, verbose_name='Третья часть слогана')),
                ('technologies_title', models.CharField(max_length=150, verbose_name='Заголовок секции используемых технологий')),
                ('django_title', models.CharField(max_length=50, verbose_name='Заголовок сервера')),
                ('django_description', models.CharField(max_length=500, verbose_name='Описание сервера')),
                ('postgresql_title', models.CharField(max_length=50, verbose_name='Заголовок БД')),
                ('postgresql_description', models.CharField(max_length=500, verbose_name='Описание БД')),
                ('vue_title', models.CharField(max_length=50, verbose_name='Заголовок фронта')),
                ('vue_description', models.CharField(max_length=500, verbose_name='Описание фронта')),
                ('contact_pretitle', models.CharField(max_length=50, verbose_name='Предзаголовок секции связи')),
                ('contact_title', models.CharField(max_length=150, verbose_name='Заголовок секции связи')),
                ('contact_description', models.CharField(max_length=300, verbose_name='Описание секции связи')),
                ('name_label', models.CharField(max_length=20, verbose_name='Лейбл имени')),
                ('name_placeholder', models.CharField(max_length=50, verbose_name='Плейсхолдер имени')),
                ('email_label', models.CharField(max_length=20, verbose_name='Лейбл емайла')),
                ('email_placeholder', models.CharField(max_length=50, verbose_name='Плейсхолдер емайла')),
                ('message_label', models.CharField(max_length=20, verbose_name='Лейбл сообщения')),
                ('message_placeholder', models.CharField(max_length=50, verbose_name='Плейсхолдер сообщения')),
                ('privacy_text', models.CharField(max_length=50, verbose_name='Сообщение согласия')),
                ('privacy_link', models.CharField(max_length=50, verbose_name='Сообщение-ссылка на условия')),
                ('review_title', models.CharField(max_length=150, verbose_name='Заголовок секции отзывов')),
                ('review_description', models.CharField(max_length=300, verbose_name='Описание секции отзывов')),
                ('first_text', models.CharField(max_length=50, verbose_name='Текст певрого отзыва')),
                ('first_author', models.CharField(max_length=50, verbose_name='Автор певрого отзыва')),
                ('first_post', models.CharField(max_length=50, verbose_name='Должность певрого автора')),
                ('second_text', models.CharField(max_length=50, verbose_name='Текст второго отзыва')),
                ('second_author', models.CharField(max_length=50, verbose_name='Автор второго отзыва')),
                ('second_post', models.CharField(max_length=50, verbose_name='Должность второго автора')),
                ('third_text', models.CharField(max_length=50, verbose_name='Текст третьего отзыва')),
                ('third_author', models.CharField(max_length=50, verbose_name='Автор третьего отзыва')),
                ('third_post', models.CharField(max_length=50, verbose_name='Должность третьего автора')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главные страницы',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='en', max_length=6, verbose_name='Язык')),
                ('projects_link', models.CharField(max_length=30, verbose_name='Проекты')),
                ('skills_link', models.CharField(max_length=30, verbose_name='Скиллы')),
                ('about_link', models.CharField(max_length=30, verbose_name='Обо мне')),
                ('telegram_button', models.CharField(max_length=30, verbose_name='Кнопка связаться')),
            ],
            options={
                'verbose_name': 'Навигационная панель',
                'verbose_name_plural': 'Навигационные панели',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='en', max_length=6, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Страница с Конфиденциальностью',
                'verbose_name_plural': 'Страницы с Конфиденциальностью',
            },
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='en', max_length=6, verbose_name='Язык')),
                ('back_button', models.CharField(max_length=20, verbose_name='Назад')),
            ],
            options={
                'verbose_name': 'Страница проектов',
                'verbose_name_plural': 'Страницы проектов',
            },
        ),
        migrations.CreateModel(
            name='SkillsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='en', max_length=6, verbose_name='Язык')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Страница скиллов',
                'verbose_name_plural': 'Страницы скиллов',
            },
        ),
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='en', max_length=6, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Страница с условиями',
                'verbose_name_plural': 'Страницы с условиями',
            },
        ),
    ]
