# Generated by Django 4.1.5 on 2023-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookieelement',
            name='button',
            field=models.CharField(max_length=60, verbose_name='Кнопка'),
        ),
        migrations.AlterField(
            model_name='cookieelement',
            name='element_text',
            field=models.CharField(max_length=60, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='cookieelement',
            name='link',
            field=models.CharField(max_length=60, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='about_link',
            field=models.CharField(max_length=60, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='cookies_link',
            field=models.CharField(max_length=60, verbose_name='Cookies'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='overview_link',
            field=models.CharField(max_length=60, verbose_name='Обзор'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='privacy_link',
            field=models.CharField(max_length=60, verbose_name='Конфиденциальность'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='projects_link',
            field=models.CharField(max_length=60, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='skills_link',
            field=models.CharField(max_length=60, verbose_name='Скиллы'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='terms_link',
            field=models.CharField(max_length=60, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='contact_button',
            field=models.CharField(max_length=50, verbose_name='Свяжитесь со мной'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='email_label',
            field=models.CharField(max_length=50, verbose_name='Лейбл емайла'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='first_string',
            field=models.CharField(max_length=50, verbose_name='Первая часть слогана'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='get_started_button',
            field=models.CharField(max_length=50, verbose_name='Начните'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='learn_more_button',
            field=models.CharField(max_length=50, verbose_name='Узнать больше'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='message_label',
            field=models.CharField(max_length=50, verbose_name='Лейбл сообщения'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='name_label',
            field=models.CharField(max_length=50, verbose_name='Лейбл имени'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='projects_button',
            field=models.CharField(max_length=50, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_string',
            field=models.CharField(max_length=50, verbose_name='Вторая часть слогана-ссылка'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='send_message_button',
            field=models.CharField(max_length=50, verbose_name='Отправить заявку'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='third_string',
            field=models.CharField(max_length=50, verbose_name='Третья часть слогана'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='about_link',
            field=models.CharField(max_length=60, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='projects_link',
            field=models.CharField(max_length=60, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='skills_link',
            field=models.CharField(max_length=60, verbose_name='Скиллы'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='telegram_button',
            field=models.CharField(max_length=60, verbose_name='Кнопка связаться'),
        ),
        migrations.AlterField(
            model_name='projectspage',
            name='back_button',
            field=models.CharField(max_length=50, verbose_name='Назад'),
        ),
    ]
