# Generated by Django 4.1.5 on 2023-03-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_cookieelement_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='concept_description',
            field=models.CharField(max_length=1000, verbose_name='Описание концепта'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='deploy_description',
            field=models.CharField(max_length=1000, verbose_name='Описание деплоя'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='discussion_description',
            field=models.CharField(max_length=1000, verbose_name='Описание обсуждения'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='django_description',
            field=models.CharField(max_length=1000, verbose_name='Описание сервера'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='postgresql_description',
            field=models.CharField(max_length=1000, verbose_name='Описание БД'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='server_dev_description',
            field=models.CharField(max_length=1000, verbose_name='Описание разработки сервера и бд'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='test_description',
            field=models.CharField(max_length=1000, verbose_name='Описание тестирования'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='ui_dev_description',
            field=models.CharField(max_length=1000, verbose_name='Описание разработки UI'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='vue_description',
            field=models.CharField(max_length=1000, verbose_name='Описание фронта'),
        ),
    ]
