# Generated by Django 4.1.5 on 2023-03-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_mainpage_concept_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='introduce_description',
            field=models.CharField(max_length=1000, verbose_name='Описание секции вступления'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='project_description',
            field=models.CharField(max_length=1000, verbose_name='Описание секции проектов'),
        ),
    ]
