# Generated by Django 4.1.5 on 2023-03-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_mainpage_introduce_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillspage',
            name='backend_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='backend - описание'),
        ),
        migrations.AddField(
            model_name='skillspage',
            name='backend_title',
            field=models.CharField(blank=True, max_length=20, verbose_name='backend - заголовок'),
        ),
        migrations.AddField(
            model_name='skillspage',
            name='frontend_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='frontend - описание'),
        ),
        migrations.AddField(
            model_name='skillspage',
            name='frontend_title',
            field=models.CharField(blank=True, max_length=20, verbose_name='frontend - заголовок'),
        ),
        migrations.AddField(
            model_name='skillspage',
            name='other_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Другое - описание'),
        ),
        migrations.AddField(
            model_name='skillspage',
            name='other_title',
            field=models.CharField(blank=True, max_length=20, verbose_name='Другое - заголовок'),
        ),
    ]
