# Generated by Django 4.1.5 on 2023-03-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_skillspage_backend_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='about_text',
            field=models.TextField(default='', verbose_name='Текст о себе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='download_button',
            field=models.CharField(default='', max_length=40, verbose_name='Кнопка для скачивания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='resume_text',
            field=models.CharField(default='', max_length=60, verbose_name='Заголовок для блока резюме'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='', max_length=40, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
