# Generated by Django 4.1.5 on 2023-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_aboutpage_about_text_aboutpage_download_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='error_message',
            field=models.CharField(blank=True, max_length=60, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='success_message',
            field=models.CharField(blank=True, max_length=60, verbose_name='Сообщение об успехе'),
        ),
    ]
