# Generated by Django 4.1.5 on 2023-03-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_mainpage_error_message_mainpage_success_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='feedback_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание секции связи'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='feedback_error_message',
            field=models.CharField(blank=True, max_length=60, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='feedback_message_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Лейбл сообщения'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='feedback_message_placeholder',
            field=models.CharField(blank=True, max_length=50, verbose_name='Плейсхолдер сообщения'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='feedback_success_message',
            field=models.CharField(blank=True, max_length=60, verbose_name='Сообщение об успехе'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='feedback_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок секции связи'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='rate_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Предзаголовок секции связи'),
        ),
    ]
