# Generated by Django 4.1.5 on 2023-03-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_mainpage_feedback_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='feedback_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание фидбека'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='feedback_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок фидбека'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='rate_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок оценки'),
        ),
    ]
