# Generated by Django 4.1.5 on 2023-03-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_mainpage_feedback_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='rate_title_success',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок оценки в случае отправки'),
        ),
    ]
