# Generated by Django 4.1.5 on 2023-03-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_mainpage_rate_title_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='en', max_length=6, verbose_name='Язык')),
                ('rate_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок оценки')),
                ('rate_title_success', models.CharField(blank=True, max_length=50, verbose_name='Заголовок оценки в случае отправки')),
                ('feedback_title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок фидбека')),
                ('feedback_description', models.CharField(blank=True, max_length=300, verbose_name='Описание фидбека')),
                ('feedback_message_label', models.CharField(blank=True, max_length=50, verbose_name='Лейбл сообщения')),
                ('feedback_message_placeholder', models.CharField(blank=True, max_length=50, verbose_name='Плейсхолдер сообщения')),
                ('feedback_success_message', models.CharField(blank=True, max_length=60, verbose_name='Сообщение об успехе')),
                ('feedback_error_message', models.CharField(blank=True, max_length=60, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Модуль обратной связи',
                'verbose_name_plural': 'Модули обратной связи',
            },
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='feedback_description',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='feedback_error_message',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='feedback_message_label',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='feedback_message_placeholder',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='feedback_success_message',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='feedback_title',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='rate_title',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='rate_title_success',
        ),
    ]
