# Generated by Django 4.1.5 on 2023-03-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rateelement_remove_mainpage_feedback_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateelement',
            name='send_button',
            field=models.CharField(blank=True, max_length=60, verbose_name='Кнопка отправки'),
        ),
        migrations.AddField(
            model_name='rateelement',
            name='send_button_wait',
            field=models.CharField(blank=True, max_length=60, verbose_name='Кнопка отправки - ожидание'),
        ),
    ]
