# Generated by Django 4.1.5 on 2023-03-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rateelement_send_button_rateelement_send_button_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateelement',
            name='retry',
            field=models.CharField(blank=True, max_length=60, verbose_name='Повторить'),
        ),
    ]
