# Generated by Django 4.1.5 on 2023-03-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_rename_retry_rateelement_retry_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='retry_button',
            field=models.CharField(blank=True, max_length=60, verbose_name='Повторить'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='send_message_button_wait',
            field=models.CharField(blank=True, max_length=60, verbose_name='Кнопка отправки - ожидание'),
        ),
    ]
