# Generated by Django 4.1.5 on 2023-03-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_mainpage_retry_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiespage',
            name='data',
            field=models.TextField(blank=True, max_length=100000, verbose_name='Политика'),
        ),
        migrations.AddField(
            model_name='privacypage',
            name='data',
            field=models.TextField(blank=True, max_length=100000, verbose_name='Политика'),
        ),
        migrations.AddField(
            model_name='termspage',
            name='data',
            field=models.TextField(blank=True, max_length=100000, verbose_name='Политика'),
        ),
    ]
