# Generated by Django 5.1 on 2024-08-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_cookiespage_data_privacypage_data_termspage_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillspage',
            name='backend_description',
            field=models.TextField(blank=True, verbose_name='backend - описание'),
        ),
        migrations.AlterField(
            model_name='skillspage',
            name='frontend_description',
            field=models.TextField(blank=True, verbose_name='frontend - описание'),
        ),
        migrations.AlterField(
            model_name='skillspage',
            name='other_description',
            field=models.TextField(blank=True, verbose_name='Другое - описание'),
        ),
    ]
