# Generated by Django 5.1 on 2025-01-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('about', 'About page'), ('cookie', 'Cookie page'), ('main', 'Main page'), ('privacy', 'Privacy page'), ('projects', 'Projects page'), ('skills', 'Skills page'), ('soloproj', 'Solo project page'), ('terms', 'Terms page')], max_length=20, verbose_name='Источник оценки')),
                ('rate_message', models.CharField(blank=True, max_length=500, verbose_name='Сообщение')),
                ('project_version', models.CharField(max_length=10, verbose_name='Версия приложения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user_agent', models.CharField(blank=True, max_length=2000, verbose_name='UserAgent')),
                ('screen_resolution', models.CharField(blank=True, max_length=100, verbose_name='Разрешение экрана')),
                ('browser_language', models.CharField(blank=True, max_length=100, verbose_name='Язык браузера')),
                ('timezone', models.CharField(blank=True, max_length=100, verbose_name='Временная зона')),
            ],
            options={
                'verbose_name': 'Отзыв о качестве',
                'verbose_name_plural': 'Отзывы о качестве',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('mail', models.CharField(max_length=150, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('project_version', models.CharField(blank=True, max_length=10, verbose_name='Версия приложения')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=2000, verbose_name='UserAgent')),
                ('screen_resolution', models.CharField(blank=True, max_length=100, verbose_name='Разрешение экрана')),
                ('browser_language', models.CharField(blank=True, max_length=100, verbose_name='Язык браузера')),
                ('timezone', models.CharField(blank=True, max_length=100, verbose_name='Временная зона')),
                ('cookie', models.TextField(blank=True, max_length=5000, verbose_name='Cookie')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('about', 'About page'), ('cookie', 'Cookie page'), ('main', 'Main page'), ('privacy', 'Privacy page'), ('projects', 'Projects page'), ('skills', 'Skills page'), ('soloproj', 'Solo project page'), ('terms', 'Terms page')], max_length=20, verbose_name='Источник оценки')),
                ('rate_value', models.IntegerField(blank=True, verbose_name='Оценка')),
                ('project_version', models.CharField(max_length=10, verbose_name='Версия приложения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user_agent', models.CharField(blank=True, max_length=2000, verbose_name='UserAgent')),
                ('screen_resolution', models.CharField(blank=True, max_length=100, verbose_name='Разрешение экрана')),
                ('browser_language', models.CharField(blank=True, max_length=100, verbose_name='Язык браузера')),
                ('timezone', models.CharField(blank=True, max_length=100, verbose_name='Временная зона')),
            ],
            options={
                'verbose_name': 'Оценка раздела',
                'verbose_name_plural': 'Оценки разделов',
            },
        ),
    ]
