bind = "127.0.0.1:8001"
workers = 2
user = "kajimasoys"
timeout = 120

raw_env = [
    'KAJIMASOYS_PORTFOLIO_DEBUG=$KAJIMASOYS_PORTFOLIO_DEBUG',
    'KAJIMASOYS_PORTFOLIO_ALLOWED_HOSTS=$KAJIMASOYS_PORTFOLIO_ALLOWED_HOSTS',
    'KAJIMASOYS_PORTFOLIO_SECRET_KEY=$KAJIMASOYS_PORTFOLIO_SECRET_KEY',
    'KAJIMASOYS_PORTFOLIO_POSTGRES_NAME=$KAJIMASOYS_PORTFOLIO_POSTGRES_NAME',
    'KAJIMASOYS_PORTFOLIO_POSTGRES_USER=$KAJIMASOYS_PORTFOLIO_POSTGRES_USER',
    'KAJIMASOYS_PORTFOLIO_POSTGRES_PASSWORD=$KAJIMASOYS_PORTFOLIO_POSTGRES_PASSWORD',
    'KAJIMASOYS_PORTFOLIO_POSTGRES_HOST=$KAJIMASOYS_PORTFOLIO_POSTGRES_HOST',
    'KAJIMASOYS_PORTFOLIO_POSTGRES_PORT=$KAJIMASOYS_PORTFOLIO_POSTGRES_PORT',
    'KAJIMASOYS_PORTFOLIO_CSRF_COOKIE_SECURE=$KAJIMASOYS_PORTFOLIO_CSRF_COOKIE_SECURE',
    'KAJIMASOYS_PORTFOLIO_SESSION_COOKIE_SECURE=$KAJIMASOYS_PORTFOLIO_SESSION_COOKIE_SECURE'
]
