# Generated by Django 4.1.5 on 2023-02-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mail',
            field=models.CharField(max_length=150, verbose_name='Email'),
        ),
    ]
