# Generated by Django 4.1.5 on 2023-03-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_rate_browser_language_rate_cookies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('about', 'About page'), ('cookie', 'Cookie page'), ('main', 'Main page'), ('privacy', 'Privacy page'), ('projects', 'Projects page'), ('skills', 'Skills page'), ('soloproj', 'Solo project page'), ('terms', 'Terms page')], max_length=20, verbose_name='Источник оценки')),
                ('rate_message', models.CharField(blank=True, max_length=500, verbose_name='Сообщение')),
                ('project_version', models.CharField(max_length=10, verbose_name='Версия приложения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user_agent', models.CharField(blank=True, max_length=2000, verbose_name='')),
                ('screen_resolution', models.CharField(blank=True, max_length=100, verbose_name='')),
                ('browser_language', models.CharField(blank=True, max_length=100, verbose_name='')),
                ('timezone', models.CharField(blank=True, max_length=100, verbose_name='')),
            ],
            options={
                'verbose_name': 'Отзыв о качестве',
                'verbose_name_plural': 'Отзывы о качестве',
            },
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Оценка раздела', 'verbose_name_plural': 'Оценки разделов'},
        ),
        migrations.RemoveField(
            model_name='rate',
            name='cookies',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='rate_message',
        ),
    ]
