# Generated by Django 4.1.5 on 2023-03-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_feedback_alter_rate_options_remove_rate_cookies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='browser_language',
            field=models.CharField(blank=True, max_length=100, verbose_name='Язык браузера'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Разрешение экрана'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Временная зона'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_agent',
            field=models.CharField(blank=True, max_length=2000, verbose_name='UserAgent'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='browser_language',
            field=models.CharField(blank=True, max_length=100, verbose_name='Язык браузера'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Разрешение экрана'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Временная зона'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='user_agent',
            field=models.CharField(blank=True, max_length=2000, verbose_name='UserAgent'),
        ),
    ]
