# Generated by Django 4.1.5 on 2023-03-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_alter_feedback_browser_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='browser_language',
            field=models.CharField(blank=True, max_length=100, verbose_name='Язык браузера'),
        ),
        migrations.AddField(
            model_name='order',
            name='cookie',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Cookie'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_version',
            field=models.CharField(blank=True, max_length=10, verbose_name='Версия приложения'),
        ),
        migrations.AddField(
            model_name='order',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Разрешение экрана'),
        ),
        migrations.AddField(
            model_name='order',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Временная зона'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_agent',
            field=models.CharField(blank=True, max_length=2000, verbose_name='UserAgent'),
        ),
    ]
